version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    reviewers:
      - "emqx/emqx-review-board"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/.github/actions/package-macos/" # All subdirectories outside of "/.github/workflows" must be explicitly included.
    reviewers:
      - "emqx/emqx-review-board"
    schedule:
      interval: weekly
    groups:
      actions-package-macos:
        patterns:
          - "*"
