services:
  mqnamesrvssl:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq_namesrv_ssl
#    ports:
#      - 9876:9876
    volumes:
      - ./rocketmq/logs_ssl:/opt/logs
      - ./rocketmq/store_ssl:/opt/store
    environment:
      JAVA_OPT: "-Dtls.server.mode=enforcing"
    command: ./mqnamesrv
    networks:
      - emqx_bridge

  mqbrokerssl:
    image: apache/rocketmq:4.9.4
    container_name: rocketmq_broker_ssl
#    ports:
#      - 10909:10909
#      - 10911:10911
    volumes:
      - ./rocketmq/logs_ssl:/opt/logs
      - ./rocketmq/store_ssl:/opt/store
      - ./rocketmq/conf_ssl/broker.conf:/etc/rocketmq/broker.conf
      - ./rocketmq/conf_ssl/plain_acl.yml:/home/rocketmq/rocketmq-4.9.4/conf/plain_acl.yml
    environment:
        NAMESRV_ADDR: "rocketmq_namesrv_ssl:9876"
        JAVA_OPTS: " -Duser.home=/opt -Drocketmq.broker.diskSpaceWarningLevelRatio=0.99"
        JAVA_OPT_EXT: "-server -Xms512m -Xmx512m -Xmn512m -Dtls.server.mode=enforcing"
    command: ./mqbroker -c /etc/rocketmq/broker.conf
    depends_on:
      - mqnamesrvssl
    networks:
      - emqx_bridge

networks:
  emqx_bridge:
    driver: bridge
