services:
  datalayers_server_tls:
    container_name: datalayers_tls
    image: datalayers/datalayers:${DATALAYERS_TAG}
    expose:
      # gRPCs
      - "8362"
      # HTTPS
      - "8363"
    environment:
      DATALAYERS_SERVER__TIMEZONE: "Etc/GMT"
      DATALAYERS_SERVER__ADDR: "0.0.0.0:8362"
      DATALAYERS_SERVER__HTTP: "0.0.0.0:8363"
      DATALAYERS_TS_ENGINE__SCHEMALESS__AUTO_ALTER_TABLE: "true"
      DATALAYERS_SERVER__TLS__KEY: "/etc/datalayers/key.pem"
      DATALAYERS_SERVER__TLS__CERT: "/etc/datalayers/cert.pem"
    volumes:
      - ./certs/ca.crt:/etc/datalayers/cacert.pem
      - ./datalayers/server.crt:/etc/datalayers/cert.pem
      - ./datalayers/server.key:/etc/datalayers/key.pem
    restart: always
    networks:
      - emqx_bridge
