services:
  rabbitmq:
    container_name: rabbitmq
    image: public.ecr.aws/docker/library/rabbitmq:3.11-management

    restart: always
    expose:
      - "15672"
      - "5672"
      - "5671"
    # We don't want to take ports from the host
    #ports:
    #   - "15672:15672"
    #   - "5672:5672"
    #   - "5671:5671"
    volumes:
      - ./certs/ca.crt:/opt/certs/ca.crt
      - ./certs/server.crt:/opt/certs/server.crt
      - ./certs/server.key:/opt/certs/server.key
      - ./rabbitmq/20-tls.conf:/etc/rabbitmq/conf.d/20-tls.conf
    networks:
      - emqx_bridge
