services:

  redis-sentinel-tls-master:
    container_name: redis-sentinel-tls-master
    image: public.ecr.aws/docker/library/redis:${REDIS_TAG}
    volumes:
      - ./redis/sentinel-tls:/usr/local/etc/redis
      - ../../apps/emqx/etc/certs:/etc/certs
    command: redis-server /usr/local/etc/redis/master.conf
    networks:
      - emqx_bridge

  redis-sentinel-tls-slave:
    container_name: redis-sentinel-tls-slave
    image: public.ecr.aws/docker/library/redis:${REDIS_TAG}
    volumes:
      - ./redis/sentinel-tls:/usr/local/etc/redis
      - ../../apps/emqx/etc/certs:/etc/certs
    command: redis-server /usr/local/etc/redis/slave.conf
    networks:
      - emqx_bridge
    depends_on:
      - redis-sentinel-tls-master

  redis-sentinel-tls:
    container_name: redis-sentinel-tls
    image: public.ecr.aws/docker/library/redis:${REDIS_TAG}
    volumes:
      - ./redis/sentinel-tls/sentinel-base.conf:/usr/local/etc/redis/sentinel-base.conf
      - ../../apps/emqx/etc/certs:/etc/certs
    depends_on:
      - redis-sentinel-tls-master
      - redis-sentinel-tls-slave
    command: >
      bash -c "cp -f /usr/local/etc/redis/sentinel-base.conf /usr/local/etc/redis/sentinel.conf &&
               redis-sentinel /usr/local/etc/redis/sentinel.conf"
    networks:
      - emqx_bridge




