receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth/server
#        tls:
#          ca_file: /etc/ca.pem
#          cert_file: /etc/server.pem
#          key_file: /etc/server.key
#      http:
#        tls:
#          ca_file: /etc/ca.pem
#          cert_file: /etc/server.pem
#          key_file: /etc/server.key

exporters:
  otlp:
    endpoint: jaeger.emqx.net:4317
    tls:
      insecure: true
  debug:
    verbosity: detailed
  file/log:
    path: /etc/otel_tcp_emqx_log.json
  file/metrics:
    path: /etc/otel_tcp_emqx_metrics.json

processors:
  batch:
    # send data immediately
    timeout: 0

extensions:
  health_check:
  zpages:
    endpoint: :55679
  basicauth/server:
    htpasswd:
      inline: |
        admin:public

service:
  extensions: [zpages, health_check, basicauth/server]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [file/log]
